/*
 * This source file was generated by the Gradle 'init' task
 */
package authservice;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;


@SpringBootApplication
//@EnableJpaRepositories(basePackages = {"authservice.repository"})
//@ComponentScan(basePackages = {"authservice.controller", "authservice.auth", "authservice.services"})
public class App {
    public String getGreeting() {
        return "Hello World!!!";
    }

    public static void main(String[] args) {

        SpringApplication.run(App.class, args);

    }
}
